# Generated by Django 5.2.8 on 2025-12-05 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0003_quizprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='flowchart_image',
            field=models.ImageField(blank=True, null=True, upload_to='flowcharts/'),
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_objects', to='EduCrew_Backend.studymaterial')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduCrew_Backend.studymaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('answer', models.TextField()),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='EduCrew_Backend.studymaterial')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
