# Generated by Django 5.2.8 on 2025-12-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0004_studymaterial_flowchart_image_flashcard_quizattempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='study_material',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='study_material',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='flowchart_image',
        ),
        migrations.DeleteModel(
            name='Flashcard',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
