# Generated by Django 5.2.8 on 2025-12-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0006_remove_studymaterial_flashcards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='material',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='material',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='flashcards_meta',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='quiz_meta',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='flashcards',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='quiz',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Flashcard',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
