# Generated by Django 5.2.8 on 2025-12-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0007_remove_quizattempt_material_remove_quizattempt_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizprogress',
            name='material',
        ),
        migrations.RemoveField(
            model_name='quizprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExportedPack',
        ),
        migrations.DeleteModel(
            name='QuizProgress',
        ),
    ]
