# Generated by Django 5.2.8 on 2025-12-06 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0008_remove_quizprogress_material_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='flashcards',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='quiz',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='flashcards_meta',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='quiz_meta',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='EduCrew_Backend.studymaterial')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.FloatField()),
                ('total', models.IntegerField()),
                ('details', models.JSONField(default=dict)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduCrew_Backend.studymaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('answer', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='EduCrew_Backend.studymaterial')),
            ],
        ),
    ]
