# Generated by Django 5.2.8 on 2025-12-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0010_remove_quizattempt_material_remove_quizattempt_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='study_materials/'),
        ),
    ]
