# Generated by Django 5.2.8 on 2025-12-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0012_presentation_presentationslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='accent_color',
            field=models.CharField(default='#0078D4', max_length=7),
        ),
        migrations.AddField(
            model_name='presentation',
            name='bg_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='presentation',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='presentation',
            name='theme_color',
            field=models.CharField(choices=[('blue', 'Professional Blue'), ('green', 'Fresh Green'), ('purple', 'Royal Purple'), ('orange', 'Vibrant Orange'), ('dark', 'Dark Theme'), ('light', 'Light Theme')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
