# Generated by Django 5.2.8 on 2025-12-10 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0013_presentation_accent_color_presentation_bg_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='python', max_length=16)),
                ('code', models.TextField()),
                ('review', models.TextField(blank=True)),
                ('debug_help', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('generated_code', models.TextField(blank=True)),
                ('sandbox_output', models.TextField(blank=True)),
                ('sandbox_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
