# Generated by Django 5.2.8 on 2025-12-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0014_codesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesession',
            name='practice_challenge',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='codesession',
            name='time_limit_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
