# Generated by Django 5.2.8 on 2025-12-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0015_codesession_practice_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesession',
            name='animation_trace',
            field=models.TextField(blank=True, default=''),
        ),
    ]
