# Generated by Django 5.2.8 on 2025-12-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0016_codesession_animation_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesession',
            name='peer_reviews',
            field=models.TextField(blank=True, default=''),
        ),
    ]
