# Generated by Django 5.2.8 on 2025-12-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0017_codesession_peer_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesession',
            name='peer_reviews',
        ),
    ]
