# Generated by Django 5.2.8 on 2025-12-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0018_remove_codesession_peer_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesession',
            name='interview_difficulty',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='codesession',
            name='interview_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesession',
            name='interview_problem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='codesession',
            name='interview_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesession',
            name='interview_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesession',
            name='is_interview',
            field=models.BooleanField(default=False),
        ),
    ]
