# Generated by Django 5.2.8 on 2025-12-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0020_projectplan_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='repo_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
