# Generated by Django 5.2.8 on 2025-12-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0021_projecttask_file_path_projecttask_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='repo_link',
        ),
    ]
