# Generated by Django 5.2.8 on 2025-12-18 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0022_remove_projecttask_file_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('original_text', models.TextField()),
                ('quality_score', models.IntegerField(blank=True, null=True)),
                ('quality_issues', models.JSONField(blank=True, default=list)),
                ('overall_feedback', models.TextField(blank=True)),
                ('similarity_percent', models.FloatField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('match_groups', models.JSONField(blank=True, default=dict)),
                ('top_sources', models.JSONField(blank=True, default=list)),
                ('raw_plagiarism_report', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
