# Generated by Django 5.2.8 on 2025-12-26 11:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0023_qualityreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('layout_config', models.JSONField()),
                ('color_scheme', models.JSONField()),
                ('fonts', models.JSONField()),
                ('uses_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('professional', 'Professional Teal'), ('academic', 'Academic Blue'), ('creative', 'Creative Orange'), ('minimal', 'Minimal Gray')], max_length=100)),
                ('description', models.TextField()),
                ('primary_color', models.CharField(max_length=7)),
                ('secondary_color', models.CharField(max_length=7)),
                ('accent_color', models.CharField(max_length=7)),
                ('text_color', models.CharField(max_length=7)),
                ('bg_color', models.CharField(max_length=7)),
                ('title_font', models.CharField(max_length=100)),
                ('body_font', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='presentationslide',
            options={'ordering': ['presentation', 'slide_number']},
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='theme_color',
        ),
        migrations.AlterUniqueTogether(
            name='presentationslide',
            unique_together={('presentation', 'slide_number')},
        ),
        migrations.AddField(
            model_name='presentation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='presentations/'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='slides_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presentation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 26, 11, 24, 1, 567938, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='diagram_type',
            field=models.CharField(choices=[('none', 'No Diagram'), ('flowchart', 'Flowchart'), ('comparison', 'Comparison Grid'), ('timeline', 'Timeline'), ('hierarchy', 'Hierarchy')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='slide_type',
            field=models.CharField(choices=[('title', 'Title Slide'), ('content', 'Content Slide'), ('conclusion', 'Conclusion Slide'), ('comparison', 'Comparison Slide'), ('process', 'Process/Flowchart Slide')], default='content', max_length=20),
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='speaker_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='pptx_file',
            field=models.FileField(blank=True, null=True, upload_to='presentations/'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presentationslide',
            name='content',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='presentationslide',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='presentation',
            index=models.Index(fields=['user', '-created_at'], name='EduCrew_Bac_user_id_d8b8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='presentation',
            index=models.Index(fields=['status'], name='EduCrew_Bac_status_eece24_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationslide',
            index=models.Index(fields=['presentation', 'slide_number'], name='EduCrew_Bac_present_3d165f_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationslide',
            index=models.Index(fields=['slide_type'], name='EduCrew_Bac_slide_t_0d1b19_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationslide',
            index=models.Index(fields=['diagram_type'], name='EduCrew_Bac_diagram_c182b6_idx'),
        ),
        migrations.RemoveField(
            model_name='presentationslide',
            name='image_alt_text',
        ),
    ]
