# Generated by Django 5.2.10 on 2026-01-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0024_presentationtemplate_presentationtheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
