# Generated by Django 5.2.10 on 2026-01-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0025_studymaterial_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='notes',
        ),
    ]
