# Generated by Django 5.2.10 on 2026-01-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0026_remove_studymaterial_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
