# Generated by Django 5.2.10 on 2026-02-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0027_studymaterial_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreview',
            name='citation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualityreview',
            name='grammar_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualityreview',
            name='requirement_match_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualityreview',
            name='style_score',
            field=models.IntegerField(default=0),
        ),
    ]
