# Generated by Django 5.2.10 on 2026-02-16 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCrew_Backend', '0028_qualityreview_citation_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectplan',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='raw_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
